---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teslamate
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: teslamate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: &dbname teslamate
        INIT_POSTGRES_HOST: &dbhost postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: &dbuser "{{ .TESLA_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbpass "{{ .TESLA_POSTGRES_PASS }}"
        INIT_POSTGRES_USER_FLAGS: "-s"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Teslmate
        TZ: Australia/Sydney
        MQTT_HOST: "mosquitto.home.svc.cluster.local"
        # MQTT_PORT: 1883
        ENCRYPTION_KEY: "{{ .TESLA_ENCRYPTION_KEY }}"
        DATABASE_HOST: *dbhost
        DATABASE_NAME: *dbname
        DATABASE_USER: *dbuser
        DATABASE_PASS: *dbpass
  dataFrom:
    - find:
        path: TESLA_
    - find:
        path: POSTGRES_
