---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres17
  namespace: database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  primaryUpdateStrategy: unsupervised
  storage:
    size: 50Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "400"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 4Gi
  monitoring:
    enablePodMonitor: true
  backup:
    target: "primary"
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/
      endpointURL: ${SECRET_S3_URL}
      # Note: serverName version needs to be inclemented
      # when recovering from an existing cnpg cluster
      serverName: &currentCluster postgres17-v2
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secrets
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: cloudnative-pg-secrets
          key: MINIO_SECRET_KEY
  # Note: previousCluster needs to be set to the name of the previous
  # cluster when recovering from an existing cnpg cluster
  bootstrap:
    recovery:
      source: &previousCluster postgres17-v1
  externalClusters:
    - name: *previousCluster
      barmanObjectStore:
        <<: *barmanObjectStore
        serverName: *previousCluster

  # # Note: This is when migrating to new major versions
  # bootstrap:
  #   initdb:
  #     import:
  #       type: monolith
  #       databases: ["*"]
  #       roles: ["*"]
  #       source:
  #         externalCluster: postgres16-v10
  # externalClusters:
  #   - name: postgres16-v10
  #     connectionParameters:
  #       # Use the correct IP or host name for the source database
  #       host: postgres16-rw.database.svc.cluster.local
  #       user: postgres
  #       # dbname: postgres
  #       # sslmode: require
  #     password:
  #       name: cloudnative-pg-secrets
  #       key: POSTGRES_SUPER_PASS
