---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./cluster16.yaml
  # - ./cluster17.yaml
  - ./externalsecret.yaml
  - ./scheduledbackup.yaml
  - ./service16.yaml
  # - ./service17.yaml
  # - ./vector16.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cloudnative-pg-cluster
      app.kubernetes.io/instance: cloudnative-pg-cluster
      app.kubernetes.io/part-of: cloudnative-pg
