---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb17
  namespace: database
  annotations:
    io.cilium/lb-ipam-ips: ${SVC_POSTGRES_ADDR}
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres17
    role: primary
