---
# yaml-language-server: $schema=https://json.schemastore.org/kustomizationapiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
labels:
  - pairs:
      app.kubernetes.io/name: rook-ceph-cluster
      app.kubernetes.io/instance: rook-ceph-cluster
      app.kubernetes.io/part-of: rook-ceph
