apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rook-ceph-alerts
  namespace: rook-ceph
spec:
  groups:
  - name: ceph.rules
    rules:
    # CSI Pod Health
    - alert: CephCSIPodRestartingFrequently
      expr: |
        increase(kube_pod_container_status_restarts_total{namespace="rook-ceph", pod=~"csi-.*"}[1h]) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "CSI pod {{ $labels.pod }} is restarting frequently"
        description: "The CSI pod {{ $labels.pod }} has restarted {{ $value }} times in the last hour"

    # Node CSI Registration
    - alert: CephCSINodeRegistrationFailing
      expr: |
        node_csi_plugin_up{plugin=~"rook-ceph.*"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "CSI registration failing on node {{ $labels.node }}"
        description: "CSI plugin {{ $labels.plugin }} is not registered on node {{ $labels.node }}"

    # PVC/PV Status
    - alert: CephPVCPending
      expr: |
        kube_persistentvolumeclaim_status_phase{phase="Pending"} == 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is pending"
        description: "PVC has been in pending state for more than 10 minutes"

    # Ceph Health
    - alert: CephClusterWarning
      expr: |
        ceph_health_status{} == 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Ceph cluster in WARNING state"
        description: "Ceph cluster has been in WARNING state for more than 5 minutes"

    - alert: CephClusterError
      expr: |
        ceph_health_status{} == 2
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Ceph cluster in ERROR state"
        description: "Ceph cluster has been in ERROR state for more than 5 minutes"

    # Node Status
    - alert: NodeNotReady
      expr: |
        kube_node_status_condition{condition="Ready",status="false"} == 1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Node {{ $labels.node }} is NotReady"
        description: "Node {{ $labels.node }} has been in NotReady state for more than 5 minutes"

    # CSI Volume Health
    - alert: CephCSIVolumeFailures
      expr: |
        ceph_csi_volume_failures_total > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "CSI Volume operations failing"
        description: "CSI volume operations are failing on node {{ $labels.node }}"
