---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./e1000e.yaml
  - ./google-coral-device.yaml
  - ./zigbee-usb.yaml
