---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-secrets
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: frigate-secrets
  dataFrom:
    - find:
        path: FRIGATE_
