# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]
        files: ^kubernetes/.*\.ya?ml$

  - repo: local
    hooks:
      - id: consistency-check
        name: Repository Consistency Check
        entry: ./scripts/validate-consistency.sh
        language: script
        pass_filenames: false
        always_run: true
        stages: [commit]
