---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openwebui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: openwebui-secret
    creationPolicy: Owner
    template:
      data:
        OPENAI_API_KEY: "{{ .OPENWEBUI_OPENAI_KEY }}"
        OPENAI_API_BASE_URL: http://litellm:4000

  dataFrom:
    - find:
        path: OPENWEBUI_
