---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: openwebui-secret
    creationPolicy: Owner
    template:
      data:
        # Database Init
        INIT_POSTGRES_DBNAME: &dbname openwebui
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .OPENWEBUI_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .OPENWEBUI_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
        DATABASE_URL: "postgres://{{ .OPENWEBUI_POSTGRES_USER }}:{{ .OPENWEBUI_POSTGRES_PASSWORD }}@postgres17-rw.database.svc.cluster.local/openwebui?sslmode=disable"
        OPENAI_API_KEY: "{{ .OPENWEBUI_OPENAI_KEY_ALL }}"
        OPENAI_API_BASE_URL: http://litellm:4000
        # Redis
        # https://docs.openwebui.com/getting-started/advanced-topics/env-configuration/#redis
        ENABLE_WEBSOCKET_SUPPORT: "true"
        WEBSOCKET_MANAGER: "redis"
        WEBSOCKET_REDIS_URL: "redis://dragonfly.database.svc.cluster.local.:6379"

  dataFrom:
    - find:
        path: OPENWEBUI_
    - find:
        path: POSTGRES_
