---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent-upgrade-p2pblocklist
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      qbittorrent-upgrade-p2pblocklist:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "@daily"
        containers:
          app:
            image:
              repository: ghcr.io/auricom/kubectl
              tag: 1.29.2@sha256:41af2d2a69bfff5c4f4dc7aafb654c46d2c44e1fca89a44b463b75c53f02f7aa
            command:
              - /bin/bash
              - -c
              - |
                #!/bin/bash

                set -o errexit
                set -o nounset

                curl --silent --location https://github.com/DavidMoore/ipfilter/releases/download/lists/ipfilter.dat.gz --output /tmp/ipfilter.dat.gz
                gunzip /tmp/ipfilter.dat.gz
                result=$(kubectl get pod --selector app.kubernetes.io/name=qbittorrent --output custom-columns=:metadata.name --namespace media)
                QBITTORRENT_POD=$(echo $result | awk '{ print $NF }')
                if [[ $QBITTORRENT_POD == *"qbittorrent"* ]]; then
                  kubectl cp /tmp/ipfilter.dat media/$QBITTORRENT_POD:/config/ipfilter.dat
                  kubectl rollout restart deployment qbittorrent --namespace media
                else
                  echo "qbittorrent deployment not found"
                  exit 1
                fi
    service:
      app:
        controller: *app
        enabled: false
    serviceAccount:
      create: false
      name: jobs
