apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:YWKYfN0TlQBpxpZdWSpi6l/UT0G95rd47m1FUujowckFGCKJ,iv:ri6nfxMt72IyZDOVYoFCOUfL6yeMac2pddMQQJWUCn0=,tag:U+oJy4Hu15q9SSRcbZkb8A==,type:str]
    credentials.json: ENC[AES256_GCM,data:MiCo6DAzsEAf2LxiGh+4ynd2FfF0THmLnw/gs/PWdY3nFQOuQT2PBV3hAKP8nAFy49hdcA9gafwBHEdiNHzoW+YEaX1BKzSEUnFg2gEAqQafPKrLyistTKQFXrTENly95U2n0NQ40Pzj2ASR+uAntVuGYODixLX36q/5PQ/SmfebaXlO7NuPx3cvZmgFHrlr+RJE88HsxgyFrx/wjPtgOCdU5aV9nlEBgOQMcAwF+A==,iv:+2dSgD+ht6RfF5FPXEFr27y5E/uWX8bUBmsDjpX8uR8=,tag:bIeXhaCQeaspqxdJjZOskA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMK3dnMnZVMEphaGhZUFJT
            dzgyNFNpSVdJNWl0TGNCeU4veVV2VmFodTNNCmRWd1AzYWdtZCtmTm0wZEZTVzQ5
            RTU5ZWFLYWdhUHFrTEd1Ym0xOTVTT2cKLS0tIE1nMTk5V0d0UWdTc2kyZ1RxZEZ2
            SWl0VEd3MW9IaTlDNlJxbWFoU000NjQK7g3PCcaLxvJiiSCrtL6DM26i5261E3JC
            H4BfsAeEe14SL6mJmQ7okYP2sG7zA+X1awDhZB5KiFRWRg+eX+d5/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T10:16:18Z"
    mac: ENC[AES256_GCM,data:0mYfm/z0PXs6T+KasBJKtWPnYFrBrcaomuuiYEa3sOnshr84VFVb6QcxG4yoeO6eGMWYGTPLSMGOLKGtz9KPeGLVXEuMd8tdwD3o1CP2RqgVqoluGqWs2JKmtWP/VLKqiMoZzqRsQ3cCGENyUD7IjmoW8WoUKH+TvDlEbEwjCB0=,iv:tem72RkIJ5RHBU6D6qFU4a1jcnbg2cTAxv7vPDamm00=,tag:emmFEPHfyD30/l57s1iyqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
