---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: litellm-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: litellm-configmap
            items:
              - key: litellm.yaml
      data:
        # Postgres database
        INIT_POSTGRES_DBNAME: &dbname litellm
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .LITELLM_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LITELLM_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - find:
        path: LITELLM_
    - find:
        path: POSTGRES_
