---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: "{{ .GF_ADMIN_USER }}"
        admin-password: "{{ .GF_ADMIN_PASS }}"

        # Database configuration
        GF_DATABASE_USER: &dbuser "{{ .GF_POSTGRES_USER }}"
        GF_DATABASE_PASSWORD: &dbpass "{{ .GF_POSTGRES_PASS }}"
        GF_DATABASE_HOST: &dbhost postgres-rw.database.svc.cluster.local
        GF_DATABASE_NAME: &dbname grafana
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        TESLAMATE_POSTGRES_USER: "{{ .TESLA_POSTGRES_USER }}"
        TESLAMATE_POSTGRES_PASS: "{{ .TESLA_POSTGRES_PASS }}"
  dataFrom:
    - find:
        path: GF_
    - find:
        path: TESLA_
    - find:
        path: POSTGRES_

---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Database configuration
        GF_DATABASE_USER: &dbuser "{{ .GF_POSTGRES_USER }}"
        GF_DATABASE_PASSWORD: &dbpass "{{ .GF_POSTGRES_PASS }}"
        GF_DATABASE_HOST: &dbhost postgres16-rw.database.svc.cluster.local
        GF_DATABASE_NAME: &dbname grafana
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        TESLAMATE_POSTGRES_USER: "{{ .TESLA_POSTGRES_USER }}"
        TESLAMATE_POSTGRES_PASS: "{{ .TESLA_POSTGRES_PASS }}"
  dataFrom:
    - find:
        path: GF_
    - find:
        path: TESLA_
    - find:
        path: POSTGRES_
