---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: cert-manager-secret
  data:
    - remoteRef:
        key: CLOUDFLARE_API_TOKEN
      secretKey: api-token
