---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mosquitto
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.20
              pullPolicy: IfNotPresent
            command: [ "/bin/sh", "-c" ]
            args: [ "cp /tmp/secret/* /mosquitto/external_config/ && chmod 0700 /mosquitto/external_config/mosquitto_pwd && mosquitto_passwd -U /mosquitto/external_config/mosquitto_pwd" ]
        containers:
          app:
            image:
              repository: eclipse-mosquitto
              tag: 2.0.20
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities: { drop: ["ALL"] }
            resources:
              limits: &resources
                memory: 16Mi
              requests:
                <<: *resources
                cpu: 10m
        pod:
          securityContext:
            runAsUser: 1883
            runAsGroup: 1883
            runAsNonRoot: true
            fsGroup: 1883
            fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SVC_MOSQUITTO_ADDR}
        ports:
          http:
            port: 1883

    persistence:
      config:
        existingClaim: mosquitto
        globalMounts:
          - path: /data

      config-file:
        type: configMap
        name: mosquitto-configmap
        globalMounts:
          - path: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
            readOnly: true

      secret-file:
        type: secret
        name: mosquitto-secret
        advancedMounts:
          mosquitto:
            init-config:
              - path: /tmp/secret

      external-config:
        type: emptyDir
        globalMounts:
          - path: /mosquitto/external_config
