---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: docker.io/library/eclipse-mosquitto
              tag: 2.0.20@sha256:deae95623b9d5c6ca5e264380629db53b992106d436b56d42f7c8df46b41b96f
            command: ["/bin/sh", "-c"]
            args: ["cp /tmp/secret/* /mosquitto/external_config/ && mosquitto_passwd -U /mosquitto/external_config/mosquitto_pwd"]
        containers:
          main:
            image:
              repository: docker.io/library/eclipse-mosquitto
              tag: 2.0.20@sha256:deae95623b9d5c6ca5e264380629db53b992106d436b56d42f7c8df46b41b96f
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              limits: &resources
                memory: 16Mi
              requests:
                <<: *resources
                cpu: 10m
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SVC_MOSQUITTO_ADDR}
        ports:
          http:
            port: 1883
    persistence:
      config:
        enabled: true
        existingClaim: mosquitto
        globalMounts:
          - path: /data
      config-file:
        type: configMap
        name: mosquitto-configmap
        advancedMounts:
          main:
            main:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
      # venus-file:
      #   type: configMap
      #   name: venus-configmap
      #   advancedMounts:
      #     main:
      #       main:
      #         - path: /mosquitto/config/venus-broker.conf
      #           subPath: venus-broker.conf
      secret-file:
        type: secret
        name: mosquitto-secret
        advancedMounts:
          main:
            init-config:
              - path: /tmp/secret
      external-config:
        type: emptyDir
        globalMounts:
          - path: /mosquitto/external_config
