---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus-cni
spec:
  interval: 30m
  chart:
    spec:
      chart: multus-cni
      version: v4.2.2
      sourceRef:
        kind: HelmRepository
        name: multus-cni
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.2.2@sha256:9ff248dab2bbc7962b8774a444ea5a307154c6b721b07cc951ab06d0a0144be8
    cni:
      version: "1.2.0"
      type: multus
      confDir: /var/lib/cni/conf.d
      binDir: /var/lib/cni/bin
      kubeconfig: /etc/cni/net.d/multus.d/multus.kubeconfig
      logLevel: verbose
      logToStderr: true
      logFile: /var/log/multus.log
      capabilities:
        portMappings: true
      readinessindicatorfile: /var/run/multus/readiness
      namespaceIsolation: true
      clusterNetwork: cilium
    pod:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 64Mi
      securityContext:
        privileged: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
    tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
