---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

# Taskfile for Rook Ceph maintenance operations
# Used for cleanup during cluster rebuilds when resources get stuck

vars:
  ROOK_NAMESPACE: rook-ceph

tasks:

  remove-finalizers:
    desc: Remove finalizers from stuck Rook Ceph resources (use during failed cleanup)
    prompt: This will forcibly remove finalizers from all Rook Ceph resources. Continue?
    cmds:
      - echo "Removing finalizers from CephBlockPools..."
      - for: { var: BLOCKPOOLS, split: "\n" }
        cmd: |
          [ -n "{{.ITEM}}" ] && kubectl patch cephblockpool {{.ITEM}} -n {{.ROOK_NAMESPACE}} -p '{"metadata":{"finalizers":[]}}' --type=merge && echo "  ✓ {{.ITEM}}" || true
      - echo "Removing finalizers from CephFileSystems..."
      - for: { var: FILESYSTEMS, split: "\n" }
        cmd: |
          [ -n "{{.ITEM}}" ] && kubectl patch cephfilesystem {{.ITEM}} -n {{.ROOK_NAMESPACE}} -p '{"metadata":{"finalizers":[]}}' --type=merge && echo "  ✓ {{.ITEM}}" || true
      - echo "Removing finalizers from CephObjectStores..."
      - for: { var: OBJECTSTORES, split: "\n" }
        cmd: |
          [ -n "{{.ITEM}}" ] && kubectl patch cephobjectstore {{.ITEM}} -n {{.ROOK_NAMESPACE}} -p '{"metadata":{"finalizers":[]}}' --type=merge && echo "  ✓ {{.ITEM}}" || true
      - echo "Removing finalizers from CephCluster..."
      - for: { var: CLUSTERS, split: "\n" }
        cmd: |
          [ -n "{{.ITEM}}" ] && kubectl patch cephcluster {{.ITEM}} -n {{.ROOK_NAMESPACE}} -p '{"metadata":{"finalizers":[]}}' --type=merge && echo "  ✓ {{.ITEM}}" || true
      - echo "✅ Finalizer removal complete"
    vars:
      BLOCKPOOLS:
        sh: kubectl get cephblockpool -n {{.ROOK_NAMESPACE}} --no-headers -o custom-columns=':metadata.name' 2>/dev/null || true
      FILESYSTEMS:
        sh: kubectl get cephfilesystem -n {{.ROOK_NAMESPACE}} --no-headers -o custom-columns=':metadata.name' 2>/dev/null || true
      OBJECTSTORES:
        sh: kubectl get cephobjectstore -n {{.ROOK_NAMESPACE}} --no-headers -o custom-columns=':metadata.name' 2>/dev/null || true
      CLUSTERS:
        sh: kubectl get cephcluster -n {{.ROOK_NAMESPACE}} --no-headers -o custom-columns=':metadata.name' 2>/dev/null || true
    preconditions:
      - which kubectl

  toolbox:
    desc: Open a shell in the Rook Ceph toolbox pod
    cmd: kubectl -n {{.ROOK_NAMESPACE}} exec -it deploy/rook-ceph-tools -- bash
    preconditions:
      - kubectl -n {{.ROOK_NAMESPACE}} get deploy/rook-ceph-tools
      - which kubectl

  status:
    desc: Show Ceph cluster status
    cmd: kubectl -n {{.ROOK_NAMESPACE}} exec deploy/rook-ceph-tools -- ceph status
    preconditions:
      - kubectl -n {{.ROOK_NAMESPACE}} get deploy/rook-ceph-tools
      - which kubectl

  health:
    desc: Show Ceph cluster health details
    cmd: kubectl -n {{.ROOK_NAMESPACE}} exec deploy/rook-ceph-tools -- ceph health detail
    preconditions:
      - kubectl -n {{.ROOK_NAMESPACE}} get deploy/rook-ceph-tools
      - which kubectl

  osd-status:
    desc: Show OSD status and tree
    cmds:
      - kubectl -n {{.ROOK_NAMESPACE}} exec deploy/rook-ceph-tools -- ceph osd status
      - kubectl -n {{.ROOK_NAMESPACE}} exec deploy/rook-ceph-tools -- ceph osd tree
    preconditions:
      - kubectl -n {{.ROOK_NAMESPACE}} get deploy/rook-ceph-tools
      - which kubectl
