---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpoller
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: unpoller-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        UP_UNIFI_DEFAULT_USER: '{{ .UNIFI_DEFAULT_USER }}'
        UP_UNIFI_DEFAULT_PASS: '{{ .UNIFI_DEFAULT_PASS }}'
  dataFrom:
    - find:
        path: UNIFI_
