---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: NAMESPACE
resources:
  - ./helmrelease.yaml
  # - ./externalsecret.yaml    # If needed
  # - ./rbac.yaml             # If needed
  # - ./config/               # If needed
