---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: photoprism-secrets
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: photoprism-secrets

  data:
    - remoteRef:
        key: PHOTOPRISM_ADMIN_PASSWORD
      secretKey: PHOTOPRISM_ADMIN_PASSWORD
