---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-ca
  namespace: network
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDfTCCAmWgAwIBAgIEZnqBZDANBgkqhkiG9w0BAQsFADBrMQswCQYDVQQGEwJV
    UzERMA8GA1UECAwITmV3IFlvcmsxETAPBgNVBAcMCE5ldyBZb3JrMRYwFAYDVQQK
    DA1VYmlxdWl0aSBJbmMuMQ4wDAYDVQQLDAVVbmlGaTEOMAwGA1UEAwwFVW5pRmkw
    HhcNMjQwNjI1MDgzNTQ4WhcNMjYwOTI4MDgzNTQ4WjBrMQswCQYDVQQGEwJVUzER
    MA8GA1UECAwITmV3IFlvcmsxETAPBgNVBAcMCE5ldyBZb3JrMRYwFAYDVQQKDA1V
    YmlxdWl0aSBJbmMuMQ4wDAYDVQQLDAVVbmlGaTEOMAwGA1UEAwwFVW5pRmkwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDks+8p1zqyYH2kmKsLm55EpSyR
    d5s1wHzv1N4t/0jVNrDdOmH1/ZKBOSTF3mnkfZDrO2weaxsrkRy4NXI7tIKOd1Gd
    ZKdO1AWci9tuw+l6qp1shlawyniSKlYbZi5/gDkTRyRN93Xh5/7ZfszsPCQ5at/n
    6DtUM7zQHUj+ZNDEms5PRSG+bJIf6V/T6jC9qVl57igxp+ZZ9Vh5MpkKcuHVXZHo
    UAeLuLPqI+VS0TvsB15PokpiiB+ChDuTrqf+k0UyMt0hfIq4lMD9LOpyY1POT2PC
    +MsaExTtn0NckGYnguUE2a6ZKsdDidwUEAJjo+UmX471+WGe6r7NWpQgFhwRAgMB
    AAGjKTAnMBAGA1UdEQQJMAeCBVVuaUZpMBMGA1UdJQQMMAoGCCsGAQUFBwMBMA0G
    CSqGSIb3DQEBCwUAA4IBAQBAv8TivZmdOM5WVADluCur2HGfSXN0IHQpMJkuQpSo
    PY75NiUCZNqCUI4vR7cRwtyIaEyuA1PvQsD6+1+hbbeEZz1OJBIsbe6YLSIUEDsf
    X+uPcgigRLFuSi3ljZlj+VQoLNBz34g2tOavnNKxn9ie11Wm6VTS51zrahen3lPO
    p2nEp8S4NWZbVLSQGuqt4f5s/skScj6kUyi/yADhZba+/hGt52gNVMC7/RNXZ/DD
    UJlJAm1MGcaZkQ3z7wLONVAXYS6ywDdFMEkVfSOSJQXhS0fkEWb7bJNARlCQKjS9
    lkgWwN8GOkvXcGziTICWv/1/mIcuGmm0f9l1DBKPb1hR
    -----END CERTIFICATE-----
