---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app multus-cni
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cilium
  interval: 10m
  retryInterval: 1m
  path: ./kubernetes/apps/kube-system/multus-cni/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
