apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:cmByQ3o/IBf9XtwMDP+B+KsAtBmdD72ycWh3aNJSjFYO8bTXVjsVpwzHVi6SRjYE9iAcqY4=,iv:f3KAaCZP6o5i6Qndj8zhwXC+SdM3nCsSheC4/lZxu9o=,tag:Ml7PT+1BwXqlufkNjLDs/Q==,type:str]
sops:
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpLzJQUjEweDJ5aDBZNHQz
            c0VReTd3aVJ4cWdZQU16L3lBc2wyMitXMTJFCnpKVTZ2S2l0dDRrcWNEemRzWklM
            QUh4amdnd0hsNGpxa1E3NVl6VlArTHcKLS0tIDhheWZkTkoxNUNvbzcvdzJvS2I1
            MFJSMFo3c1QyUjdNeWZvcGJFanRRbDAKVyOmkbkK7fHnrVKRnm6uudkQi+rqg3NS
            bXHq/AxBEkNRGkBP7g7ewO5zJuGI8Q7X6Bo8DRZOPGAZhL/UIyRfLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T10:38:50Z"
    mac: ENC[AES256_GCM,data:VMMVDiXIo2dud1bTTVdnPghvhJnlJzsAz7aBA6y6zw37WHMm3bLNrezeOkEwh2En/NAWbE7gHWLwQc9OyJlMl9yfaGEsFDjbUDorxTzzO0MlW3qoClhiPK7wTuU5KHMQmC859irOk565QpXXDJeIUY0j4wbcUs4cFQXc75aNX84=,iv:DaYxJZm+Rvhe8Re2atokTx+fZy2d4SRFUylIoY/9weE=,tag:iSUyogONpaIGM9+JOGuEGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
